### PR TITLE
guidance for users joining events

### PR DESCRIPTION
**Pull request by prakal**

### CODE REVIEW

**Comment by arosenberg01** [comment]
Looks good, although I'd like to get Khoa's PR thing sorted out first before we merge yours if that's ok. Also, what is the purpose of 'app.use(express.static(path.join(__dirname, '../lib')));' in server/app.js?

**Comment by prakal** [comment]
Yeah, go ahead and fix Khoa's before merging mine. Also, good catch. I believe I put that line in there to help with serving the angular payments in my localhost, since the postinstall bower script in npm install is not running in ubuntu. I'll do another commit in which I can remove that line.

**Comment by prakal** [comment]
Some UI changes (letting the user know they have committed to joining, decrementing the threshold, incrementing the committed people and money) have not been fully implemented yet, might blow them up depending on what direction we take today.

**Comment by sentilesdal** [comment]
Looks good to me.

**Pull request merged**
