### PR TITLE
Authentication, code clean up, sessions, etc

### PR DESCRIPTION
**Pull request by kphed**

### CODE REVIEW

**Comment by arosenberg01** [comment]
Looks like good work Khoa. Has it been tested on Heroku?

**Comment by prakal** [comment]
I'm going thru the code, and will test on Heroku.

**Comment by arosenberg01** [comment]
I'm not sure about a CDN, but the module got installed and was working successfully when I deployed it to my own heroku instance.

**Comment by prakal** [comment]
No worries Ansel. I resolved it by putting it in bower.json. Going to go thru the code, merge it, and make sure it works on Heroku.

**Pull request merged**
