### PR TITLE
New changes on top of shortly angular base

### PR DESCRIPTION
**Pull request by kphed**
- Integrate OAuth for Google and Facebook
- Clean up angular signin.html and signup.html
- Add appropriate routing for OAuth
- Other minor changes/fixes
- Remove redundant login.hbs and signup.hbs files

### CODE REVIEW

**Comment by arosenberg01** [comment]
I'm not very good with OAuth/Passport, but this all looks solid! Nice job Khoa. Approved

**Comment by kphed** [comment]
Thanks Ansel!

**Comment by prakal** [comment]
Looks great Khoa. Gonna merge it. Just have to regen our keys before we deploy.

**Comment by kphed** [comment]
Thanks Pranav -- see you guys tomorrow, we'll hammer it all out then

**Pull request merged**
