### PR TITLE
Add saving of invite joining/decline to database

### PR DESCRIPTION
**Pull request by arosenberg01**

### CODE REVIEW

**Comment by arosenberg01** [comment]
Forgot to write a commit for this- user can now only 'join' or 'decline' if they have entered their venmo details. Could not get it to work for the create event button, heard we were changing that a lot anyways

**Comment by arosenberg01** [comment]
Additionally, right now it has two event pay out function invocations - both commented out. One is the actual payout invocation, the second is a test version that will make fake payments to a bot from authorized users. The real invocation still needs testing!

**Comment by sentilesdal** [comment]
it all looks pretty good to me, pranav you wanna take a look?

**Comment by prakal** [comment]
taking a look now, i thought ansel was going to do another push?

**Comment by arosenberg01** [comment]
no I'm done for the moment

**Comment by prakal** [comment]
Ok, looks good, merging.

**Pull request merged**
