### PR TITLE
Allow user to sign up for Stripe Connect account

### PR DESCRIPTION
**Pull request by arosenberg01**
Also add debit card entry form for charging users who pledge to an event, but not hooked up yet.

### CODE REVIEW

**Comment by prakal** [comment]
Looks thorough. Good job! 
Minor issue: we will need to replace Stripe API keys in a private area.

**Comment by kphed** [comment]
Nice job Ansel! Looks great as far as I can tell.  I was also wondering about those keys. Would we end up just getting new ones when we go official? Everything looks fine otherwise

**Comment by prakal** [comment]
Merging. This brings us real close to a working MVP. Good job guys!

**Comment by arosenberg01** [comment]
I was just trying to get the functionality working before worrying about API keys, these are all hooked up to my personal account as opposed to our app's account

**Pull request merged**
